### ISSUE TITLE
Allow dead letter queues to be configured by name.

### ISSUE THREAD

**Issue by jammycakes** [jammycakes/lambda-tools#3]
Suggested syntax:

```yaml
  dead_letter:
    sns: "sns topic name"
    sqs: "sqs queue name"
```

Obviously only one or the other should be specified (specifying both should error). The existing option, specifying by ARN when just a simple string is passed, should be retained.
