### ISSUE TITLE
Make configuration setting names more consistent with AWS Lambda and Terraform

### ISSUE THREAD

**Issue by jammycakes** [jammycakes/lambda-tools#4]
A number of settings in the `lambda-tools.yml` file are different from their equivalents in the AWS/boto3 API or Terraform.

Some of the differences are unavoidable due to additional requirements (e.g. for building the lambda, or for looking up AWS resources by name); however, other differences are unnecessary and should be brought into sync with the AWS conventions. The changes are as follows.

**`dead_letter`**

Currently expects a string containing an ARN of an SNS topic or SQS queue. New schema:

```yaml
dead_letter_config:
  # One of:
  target_arn: {dead_letter}
  target:
    sns:
    sqs:
```

 - [x] `dead_letter_config`:`target_arn`
 - [x] `dead_letter_config`:`target`:`sns`
 - [x] `dead_letter_config`:`target`:`sqs`

**`environment`**

Currently expects a dict of strings. New schema:

```yaml
environment:
  variables: {environment}
```
Look for a value called `variables` which should be a dict. If it isn't, move all settings into `variables` and log a warning.

 - [x] `environment`:`variables`

**`kms_key`**

Currently accepts a string, containing the key's name. DO NOT throw a warning: this should continue to be accepted.

New schema:
```yaml
kms_key:
  # One of:
  name: {kms_key}
  arn:
```
If a string is provided, move it into a dict, kms_key["name"].

 - [x] `kms_key`:`name`
 - [x] `kms_key`:`arn`

**`memory`**

This needs to be renamed to `memory_size`.

 - [x] `memory_size`

**`security_groups`, `subnets`, `vpc`**

Currently accept strings, containing the names of the above. New schema:

```yaml
vpc_config:
  # Specify the VPC by name, ID or ARN, if necessary:
  id:
  name:
  security_groups:
    # A list of either strings or dicts:
    - {security_groups}
    - name: {security_groups}
    - id:
  subnets:
    # A list of either strings or dicts
    - {subnets}
    - name: {subnets}
    - id:
```
 - [x] `vpc_config`:`id`
 - [x] `vpc_config`:`name`
   - [x] `security_groups`:(string)
   - [x] `security_groups`:`id`
   - [x] `security_groups`:`name`
   - [x] `subnets`:(string)
   - [x] `subnets`:`id`
   - [x] `subnets`:`name`

**`tracing`**:

Currently accepts a string. New schema:

```yaml
tracing_config:
  mode: {tracing}
```
 - [x] `tracing_config`:`mode`

Note that all options except `kms_key` should log warnings.
